# Generated by Django 4.0 on 2021-12-21 01:29

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'cashier',
                'verbose_name_plural': 'cashiers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'manager',
                'verbose_name_plural': 'managers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SeasonTicketHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('passport_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('inprogress', 'In progress'), ('complited', 'Complited'), ('canceled', 'Canceled')], default='inprogress', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.sector')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticketing.seasonticketholder')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.seat')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('played', 'Played'), ('planned', 'Planned')], default='planned', max_length=10)),
                ('type', models.CharField(choices=[('league', 'League'), ('cup', 'Cup'), ('international', 'International'), ('friendly', 'Friendly')], default='friendly', max_length=15)),
                ('opponent', models.CharField(max_length=50)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=500, max_digits=7)),
                ('date', models.DateTimeField(unique=True)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.match')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.seat')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.stadium')),
            ],
            options={
                'unique_together': {('match', 'seat')},
            },
        ),
    ]
