# Generated by Django 4.0 on 2021-12-21 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='seasonticket',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticketing.seat'),
        ),
        migrations.AlterUniqueTogether(
            name='seasonticket',
            unique_together={('stadium', 'seat')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('stadium', 'match', 'seat')},
        ),
        migrations.DeleteModel(
            name='Cashier',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
