# Generated by Django 4.0 on 2021-12-21 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_alter_seat_number_alter_sector_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticketing.transaction')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pay_from', models.CharField(max_length=16)),
                ('pay_to', models.CharField(max_length=16)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.seasonticket')),
            ],
            bases=('ticketing.transaction',),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticketing.transaction')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.payment')),
            ],
            bases=('ticketing.transaction',),
        ),
    ]
