# Generated by Django 4.0 on 2021-12-21 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_alter_payment_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundingPayment',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticketing.transaction')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticket')),
            ],
            bases=('ticketing.transaction',),
        ),
    ]
